### ISSUE TITLE
Distribution file loading fails

### ISSUE THREAD

**Issue by czeni** [All-less/trace-generator#14]
## Description

Random job generation fails due to an issue in loading cached distribution files *.pkl in function ``draw``.

## Experienced issue:
```bash
$ spar . --duration 1.5
  Generating jobs ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/25123 — 00:00:00
Traceback (most recent call last):
  File "/home/czentye/.local/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 678, in __setstate__
    self.__dict__.update(state)
ValueError: dictionary update sequence element #0 has length 11; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/czentye/.local/bin/spar", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/czentye/.local/lib/python3.10/site-packages/spar/cli.py", line 85, in main
    last += random_interval() / load_factor
  File "/home/czentye/.local/lib/python3.10/site-packages/spar/generate.py", line 11, in random_interval
    return draw('job_interval_dist.pkl')[0]
  File "/home/czentye/.local/lib/python3.10/site-packages/spar/utils.py", line 20, in draw
    DIST_CACHE[dist_name] = pickle.load(f)
  File "/home/czentye/.local/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 689, in __setstate__
    self.__init__()
TypeError: rv_histogram.__init__() missing 1 required positional argument: 'histogram'
```

## Environment

- OS: Ubuntu 20.04
- Python: 3.10.10
- ``scipy``: 1.8.0 - 1.10.1

## Reproduce

The abovementioned issue can be reproduced with the following code snippet:

```python3
czentye@ThinkPad-L470:~/.local/lib/python3.10/site-packages/spar/data/distributions$ python3.10
Python 3.10.10 (main, Feb  8 2023, 14:50:01) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> with open("job_interval_dist.pkl", 'rb') as f:
...     pickle.load(f)
... 
Traceback (most recent call last):
  File "/home/czentye/.local/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 678, in __setstate__
    self.__dict__.update(state)
ValueError: dictionary update sequence element #0 has length 11; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/czentye/.local/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 689, in __setstate__
    self.__init__()
TypeError: rv_histogram.__init__() missing 1 required positional argument: 'histogram'
>>> 
```

**Comment by czeni** [comment]
It must be a version issue as the synthetic data generations works with 
- Python 3.7.16
- `scipy` 1.5.0

**Comment by All-less** [comment]
Hi there, thanks for the detailed report and the exploration! It looks like the project dependencies are outdated, but I don't have much bandwidth currently to upgrade them. So I have added a head-up about dependency versions in the README. If you're interested in fixing it, you're more than welcome!

**Comment by czeni** [comment]
The problem may lie in that `scipy.stats.rv_histogram` requires a new `density` parameter in newer versions. 
Although it is "optional", it seems `pickle.load()` cannot manage it properly and that's why the object init fails.

I pushed my changes that performes the distribution creation in a more managable way.
